function [] = test_diff(name)
display('Start Speaking');
sig = audiorecorder(44100,16,1);
recordblocking(sig,3);
display('Stop Speaking');
name1 = getaudiodata(sig);
audiowrite(name,name1,44100);
Tw=25;
Ts=10;
alpha=0.97;
R = [300 3700];
M = 20;
C = 13;
L = 22;
hamming = @(N)(0.54-0.46*cos(2*pi*[0:N-1].'/(N-1)));
dis=zeros(1,9);
[ tMFCCs, ~, ~ ] = mfcc( name1, 44800, Tw, Ts, alpha, hamming, R, M, C, L );
    [speaker1,Fs]=audioread('train/t_d_diff_word/raj.wav');
    [MFCCs1,~,~] = mfcc(speaker1, Fs, Tw, Ts, alpha, hamming, R, M, C, L );
    dis(1) = dtw(tMFCCs,MFCCs1);
    display(dis(1));
    [speaker2,Fs]=audioread('train/t_d_diff_word/chaitu.wav');
    [MFCCs2,~,~] = mfcc(speaker2, Fs, Tw, Ts, alpha, hamming, R, M, C, L );
    dis(2) = dtw(tMFCCs,MFCCs2);
    display(dis(2));
    [speaker3,Fs]=audioread('train/t_d_diff_word/deepak.wav');
    [MFCCs3,~,~] = mfcc(speaker3, Fs, Tw, Ts, alpha, hamming, R, M, C, L );
    dis(3) = dtw(tMFCCs,MFCCs3);
    display(dis(3));
    [speaker4,Fs]=audioread('train/t_d_diff_word/gella.wav');
    [MFCCs4,~,~] = mfcc(speaker4, Fs, Tw, Ts, alpha, hamming, R, M, C, L );
    dis(4) = dtw(tMFCCs,MFCCs4);
    display(dis(4));
    [speaker5,Fs]=audioread('train/t_d_diff_word/challa sir.wav');
    [MFCCs5,~,~] = mfcc(speaker5, Fs, Tw, Ts, alpha, hamming, R, M, C, L );
    dis(5) = dtw(tMFCCs,MFCCs5);
    display(dis(5));
    [speaker6,Fs]=audioread('train/t_d_diff_word/akhil.wav');
    [MFCCs6,~,~] = mfcc(speaker6, Fs, Tw, Ts, alpha, hamming, R, M, C, L );
    dis(6) = dtw(tMFCCs,MFCCs6);
    display(dis(6));
    [speaker7,Fs]=audioread('train/t_d_diff_word/surya.wav');
    [MFCCs7,~,~] = mfcc(speaker7, Fs, Tw, Ts, alpha, hamming, R, M, C, L );
    dis(7) = dtw(tMFCCs,MFCCs7);
    display(dis(7));
    [speaker8,Fs]=audioread('train/t_d_diff_word/manoj.wav');
    [MFCCs8,~,~] = mfcc(speaker8, Fs, Tw, Ts, alpha, hamming, R, M, C, L );
    dis(8) = dtw(tMFCCs,MFCCs8);
    display(dis(8));
    [speaker9,Fs]=audioread('train/t_d_diff_word/sir.wav');
    [MFCCs9,~,~] = mfcc(speaker9, Fs, Tw, Ts, alpha, hamming, R, M, C, L );
    dis(9) = dtw(tMFCCs,MFCCs9);
    display(dis(9));
dis1=sort(dis);
spe={'raj','chaitanya','deepak','gella','challa sir','akhil','surya','manoj','sir'};
for i=1:1:9
    if(dis1(1)==dis(i)),display(spe(i));
    end
end